# Generated by Django 3.0.3 on 2020-02-22 13:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InspectionCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=200, verbose_name='Category')),
                ('sequence', models.IntegerField(verbose_name='Sequence')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['sequence'],
            },
        ),
        migrations.CreateModel(
            name='InspectItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspector_name', models.CharField(default=' ', max_length=100, verbose_name='Inspector Name')),
                ('category_name', models.CharField(default=' ', max_length=100, verbose_name='Category Name')),
                ('site_name', models.CharField(default=' ', max_length=100, verbose_name='Site Name')),
                ('Site_id', models.IntegerField(default='0', verbose_name='Site Id')),
                ('Inspect_id', models.IntegerField(default='0', verbose_name='Inspector Id')),
                ('Cat_id', models.IntegerField(default='0', verbose_name='Category Id')),
                ('Item_id', models.IntegerField(default='0', verbose_name='Item Id')),
                ('fieldname', models.CharField(default=' ', max_length=100, verbose_name='value')),
                ('Items', models.CharField(default=' ', max_length=100, verbose_name='items')),
                ('image', models.ImageField(upload_to=None)),
            ],
            options={
                'verbose_name': 'Inspected Item',
                'verbose_name_plural': 'Inspected Items',
            },
        ),
        migrations.CreateModel(
            name='Stoffice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(default=' ', max_length=100, verbose_name='location')),
            ],
            options={
                'verbose_name': 'ST Office',
                'verbose_name_plural': 'ST Office Locations',
            },
        ),
        migrations.CreateModel(
            name='Subsidiary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=' ', max_length=100, verbose_name='name')),
            ],
            options={
                'verbose_name': 'Subsidiary',
                'verbose_name_plural': 'Subsidiary',
            },
        ),
        migrations.CreateModel(
            name='Sites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_no', models.IntegerField(verbose_name='Site Number')),
                ('name', models.CharField(max_length=100, verbose_name='Site name')),
                ('latitude', models.FloatField(verbose_name='Latitude')),
                ('longitude', models.FloatField(verbose_name='Longitude')),
                ('state', models.CharField(max_length=50, verbose_name='State')),
                ('postcode', models.CharField(max_length=20, verbose_name='Postcode')),
                ('address', models.CharField(max_length=300, verbose_name='Address')),
                ('capacity', models.CharField(default=' ', max_length=300, verbose_name='Capacity')),
                ('incomer', models.CharField(default=' ', max_length=300, verbose_name='Incomer')),
                ('msbyear', models.CharField(default=' ', max_length=300, verbose_name='Msb Year')),
                ('stoffice', models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='inspectv1.Stoffice')),
                ('subsidiary', models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='inspectv1.Subsidiary')),
            ],
            options={
                'verbose_name': 'Site',
                'verbose_name_plural': 'Site Details',
            },
        ),
        migrations.CreateModel(
            name='ItemInCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.CharField(max_length=200, verbose_name='Item')),
                ('show_in_section', models.IntegerField(default=0, verbose_name='Show in Section')),
                ('throw_error', models.BooleanField(verbose_name='Throw error if True')),
                ('sequence', models.IntegerField(verbose_name='Sequence')),
                ('fieldtype', models.CharField(choices=[('checkbox', 'CheckBox'), ('text', 'Textfield'), ('number', 'NumberField'), ('date', 'DateField')], max_length=20)),
                ('errortype', models.CharField(choices=[('NONE', 'None'), ('STATUTORY', 'Statutory'), ('SAFETY', 'Safety'), ('ENGINEERING', 'Engineering'), ('OPERATIONS', 'Operations')], default=' ', max_length=20)),
                ('category', models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inspectv1.InspectionCategory', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Items',
                'ordering': ['sequence'],
            },
        ),
        migrations.CreateModel(
            name='InspectorDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('com_lev', models.CharField(max_length=200, verbose_name='Competency Level')),
                ('com_cert', models.CharField(max_length=200, verbose_name='Competency Certificate')),
                ('signature', models.ImageField(upload_to=None)),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Inspector Detail',
                'verbose_name_plural': 'Inspector Details',
            },
        ),
        migrations.CreateModel(
            name='InspectedItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.CharField(max_length=200, verbose_name='Item Id')),
                ('item_value', models.CharField(max_length=500, verbose_name='Item value')),
                ('item_image', models.ImageField(upload_to=None)),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inspectv1.InspectionCategory')),
                ('site_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inspectv1.Sites')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
