# Generated by Django 3.0.3 on 2020-02-12 15:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inspected_Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('S_id', models.IntegerField(default='0', verbose_name='Site Id')),
                ('Ins_id', models.IntegerField(default='0', verbose_name='Inspector Id')),
                ('c_id', models.IntegerField(default='0', verbose_name='Category Id')),
                ('item_id', models.IntegerField(default='0', verbose_name='Item Id')),
                ('field_value', models.CharField(default=' ', max_length=100, verbose_name='value')),
                ('items', models.CharField(default=' ', max_length=100, verbose_name='items')),
                ('status', models.CharField(default=' ', max_length=100, verbose_name='checked')),
            ],
        ),
        migrations.CreateModel(
            name='InspectionCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=200, verbose_name='Category')),
                ('sequence', models.IntegerField(verbose_name='Sequence')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['sequence'],
            },
        ),
        migrations.CreateModel(
            name='stoffice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Location', models.CharField(default=' ', max_length=100, verbose_name='location')),
            ],
        ),
        migrations.CreateModel(
            name='sub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=' ', max_length=100, verbose_name='name')),
            ],
        ),
        migrations.CreateModel(
            name='Sites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_no', models.IntegerField(verbose_name='Site Number')),
                ('name', models.CharField(max_length=100, verbose_name='Site name')),
                ('latitude', models.FloatField(verbose_name='Latitude')),
                ('longitude', models.FloatField(verbose_name='Longitude')),
                ('state', models.CharField(max_length=50, verbose_name='State')),
                ('postcode', models.CharField(max_length=20, verbose_name='Postcode')),
                ('address', models.CharField(max_length=300, verbose_name='Address')),
                ('capacity', models.CharField(default=' ', max_length=300, verbose_name='Capacity')),
                ('incomer', models.CharField(default=' ', max_length=300, verbose_name='Incomer')),
                ('msbyear', models.CharField(default=' ', max_length=300, verbose_name='Msb Year')),
                ('Subsdairy', models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='inspectv1.stoffice')),
            ],
            options={
                'verbose_name': 'Site',
                'verbose_name_plural': 'Sites',
            },
        ),
        migrations.CreateModel(
            name='ItemInCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.CharField(max_length=200, verbose_name='Item')),
                ('throw_error', models.BooleanField(verbose_name='Throw error if True')),
                ('sequence', models.IntegerField(verbose_name='Sequence')),
                ('fieldtype', models.CharField(choices=[('checkbox', 'CheckBox'), ('text', 'Textfield'), ('number', 'NumberField'), ('date', 'DateField')], max_length=20)),
                ('category', models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inspectv1.InspectionCategory', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Items',
                'ordering': ['sequence'],
            },
        ),
        migrations.CreateModel(
            name='InspectionDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('com_lev', models.CharField(max_length=200, verbose_name='Competancy Level')),
                ('com_cert', models.CharField(max_length=200, verbose_name='Competancy Certificate')),
                ('signature', models.ImageField(upload_to=None)),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Inspectordetail',
                'verbose_name_plural': 'Inspectordetails',
            },
        ),
    ]
