# Generated by Django 3.0.2 on 2020-01-26 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspectv1', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inspectioncatgory',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterField(
            model_name='inspectioncatgory',
            name='category',
            field=models.CharField(max_length=50, verbose_name='Category'),
        ),
    ]
