# Generated by Django 3.0.3 on 2020-02-22 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inspectv1', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inspecteditem',
            options={'verbose_name': 'Inspection Result', 'verbose_name_plural': 'Inspections Result'},
        ),
    ]
