# Generated by Django 3.0.2 on 2020-02-14 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inspectv1', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='sub',
            new_name='Subsidiary',
        ),
        migrations.AlterField(
            model_name='sites',
            name='Stoffice',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='inspectv1.SToffice'),
        ),
    ]
