# Generated by Django 3.0.3 on 2020-02-15 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inspectv1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemincategory',
            old_name='Show_In_Section',
            new_name='show_in_section',
        ),
        migrations.AlterField(
            model_name='sites',
            name='Stoffice',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='inspectv1.Stoffice'),
        ),
        migrations.AlterField(
            model_name='sites',
            name='Subsdairy',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='inspectv1.Sub'),
        ),
    ]
