# Generated by Django 3.0.3 on 2020-02-13 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inspectv1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inspect_item',
            name='sign',
        ),
    ]
