# Generated by Django 3.0.2 on 2020-01-26 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inspectv1', '0002_auto_20200126_0653'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InspectionCatgory',
            new_name='InspectionCategory',
        ),
        migrations.CreateModel(
            name='ItemInCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.CharField(max_length=20, verbose_name='Item')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inspectv1.InspectionCategory', verbose_name='Items')),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Items',
            },
        ),
    ]
