# Generated by Django 3.0.3 on 2020-02-28 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inspectv1', '0002_auto_20200222_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspecteditem',
            name='item_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inspectv1.ItemInCategory'),
        ),
    ]
