# Generated by Django 3.0.3 on 2020-02-15 10:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inspectv1', '0002_auto_20200215_0955'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InspectionDetails',
            new_name='InspectorDetails',
        ),
        migrations.AlterField(
            model_name='sites',
            name='Stoffice',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='inspectv1.Stoffice'),
        ),
        migrations.AlterField(
            model_name='sites',
            name='Subsdairy',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='inspectv1.Sub'),
        ),
    ]
