# Generated by Django 3.0.2 on 2020-02-14 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inspectv1', '0002_auto_20200214_1147'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sites',
            old_name='Stoffice',
            new_name='stoffice',
        ),
        migrations.RenameField(
            model_name='sites',
            old_name='Subsdairy',
            new_name='subsidiary',
        ),
        migrations.AlterField(
            model_name='sites',
            name='msbyear',
            field=models.CharField(default=' ', max_length=300, verbose_name='MSB Year'),
        ),
        migrations.AlterField(
            model_name='sites',
            name='stoffice',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='inspectv1.SToffice'),
        ),
    ]
