# Generated by Django 3.0.2 on 2020-02-14 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inspectv1', '0003_auto_20200214_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemincategory',
            name='errortype',
            field=models.CharField(choices=[('NONE', 'None'), ('STATUTORY', 'Statutory'), ('SAFETY', 'Safety'), ('ENGINEERING', 'Engineering'), ('OPERATIONS', 'Operations')], default=' ', max_length=20),
        ),
        migrations.AlterField(
            model_name='sites',
            name='stoffice',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='inspectv1.SToffice'),
        ),
    ]
