# Generated by Django 3.0.2 on 2020-01-26 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspectv1', '0003_auto_20200126_0809'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemincategory',
            name='throw_error',
            field=models.BooleanField(default=False, verbose_name='Throw error if True'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='inspectioncategory',
            name='category',
            field=models.CharField(max_length=200, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='itemincategory',
            name='items',
            field=models.CharField(max_length=200, verbose_name='Item'),
        ),
    ]
