# Generated by Django 3.0.3 on 2020-02-15 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inspectv1', '0003_auto_20200215_1008'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inspectordetails',
            options={'verbose_name': 'Inspector Detail', 'verbose_name_plural': 'Inspector Details'},
        ),
        migrations.AlterField(
            model_name='sites',
            name='Stoffice',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='inspectv1.Stoffice'),
        ),
        migrations.AlterField(
            model_name='sites',
            name='Subsdairy',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='inspectv1.Sub'),
        ),
    ]
