# Generated by Django 3.0.2 on 2020-02-14 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inspectv1', '0004_auto_20200214_1150'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemincategory',
            old_name='Show_In_Section',
            new_name='show_in_section',
        ),
        migrations.AlterField(
            model_name='sites',
            name='stoffice',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='inspectv1.SToffice'),
        ),
    ]
