# Generated by Django 3.0.3 on 2020-02-15 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inspectv1', '0004_auto_20200215_1051'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inspect_item',
            old_name='Inspector_Name',
            new_name='inspector_name',
        ),
        migrations.AlterField(
            model_name='sites',
            name='Stoffice',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='inspectv1.Stoffice'),
        ),
        migrations.AlterField(
            model_name='sites',
            name='Subsdairy',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='inspectv1.Sub'),
        ),
    ]
