# Generated by Django 3.0.3 on 2020-02-15 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inspectv1', '0005_auto_20200215_1055'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stoffice',
            old_name='Location',
            new_name='location',
        ),
        migrations.AlterField(
            model_name='itemincategory',
            name='errortype',
            field=models.CharField(choices=[('', 'None'), ('statutory', 'Statutory'), ('safety', 'Safety'), ('engineering', 'Engineering'), ('operations', 'Operations')], default=' ', max_length=20),
        ),
        migrations.AlterField(
            model_name='sites',
            name='Stoffice',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='inspectv1.Stoffice'),
        ),
        migrations.AlterField(
            model_name='sites',
            name='Subsdairy',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='inspectv1.Sub'),
        ),
    ]
