# Generated by Django 3.0.2 on 2020-01-27 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspectv1', '0006_auto_20200126_0841'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspectioncategory',
            name='sequence',
            field=models.IntegerField(default=1, verbose_name='Sequence'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itemincategory',
            name='sequence',
            field=models.IntegerField(default=1, verbose_name='Sequence'),
            preserve_default=False,
        ),
    ]
