# Generated by Django 3.0.3 on 2020-02-15 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inspectv1', '0006_auto_20200215_1212'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sites',
            old_name='Stoffice',
            new_name='stoffice',
        ),
        migrations.RenameField(
            model_name='sites',
            old_name='Subsdairy',
            new_name='subsdairy',
        ),
        migrations.AlterField(
            model_name='sites',
            name='stoffice',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='inspectv1.Stoffice'),
        ),
        migrations.AlterField(
            model_name='sites',
            name='subsdairy',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='inspectv1.Sub'),
        ),
    ]
