# Generated by Django 3.0.3 on 2020-02-15 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inspectv1', '0007_auto_20200215_1213'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='sub',
            new_name='Subsidiary',
        ),
        migrations.AlterModelOptions(
            name='subsidiary',
            options={'verbose_name': 'Subsidiary', 'verbose_name_plural': 'Subsidiary'},
        ),
        migrations.RemoveField(
            model_name='sites',
            name='subsdairy',
        ),
        migrations.AddField(
            model_name='sites',
            name='subsidiary',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='inspectv1.Subsidiary'),
        ),
        migrations.AlterField(
            model_name='sites',
            name='stoffice',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='inspectv1.Stoffice'),
        ),
    ]
