# Generated by Django 3.0.2 on 2020-01-27 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inspectv1', '0007_auto_20200127_0752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemincategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inspectv1.InspectionCategory', verbose_name='Category'),
        ),
    ]
