# Generated by Django 3.0.2 on 2020-01-28 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inspectv1', '0008_auto_20200127_1452'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inspectioncategory',
            options={'ordering': ['sequence'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='itemincategory',
            options={'ordering': ['sequence'], 'verbose_name': 'Item', 'verbose_name_plural': 'Items'},
        ),
    ]
