# Generated by Django 3.0.2 on 2020-01-29 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspectv1', '0009_auto_20200128_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='sites',
            name='postcode',
            field=models.CharField(default=99999, max_length=20, verbose_name='Postcode'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sites',
            name='site_no',
            field=models.IntegerField(default=101413, verbose_name='Site Number'),
            preserve_default=False,
        ),
    ]
