# Generated by Django 3.0.2 on 2020-01-29 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspectv1', '0010_auto_20200129_0020'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemincategory',
            name='fieldtype',
            field=models.CharField(choices=[('CHECKBOX', 'CheckBox'), ('TEXTFIELD', 'Textfield')], default='CHECKBOX', max_length=20),
            preserve_default=False,
        ),
    ]
