# Generated by Django 3.0.2 on 2020-01-29 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspectv1', '0011_itemincategory_fieldtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemincategory',
            name='fieldtype',
            field=models.CharField(choices=[('CHECKBOX', 'CheckBox'), ('TEXTFIELD', 'Textfield'), ('NUMERICFIELD', 'Numerical'), ('DATEFIELD', 'Date')], max_length=20),
        ),
    ]
