# Generated by Django 3.0.3 on 2020-02-15 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inspectv1', '0012_auto_20200215_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemincategory',
            name='errortype',
            field=models.CharField(choices=[('', 'None'), ('statutory', 'Statutory'), ('safety', 'Safety'), ('engineering', 'Engineering'), ('operations', 'Operations')], default=' ', max_length=20),
        ),
        migrations.AlterField(
            model_name='sites',
            name='stoffice',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='inspectv1.Stoffice'),
        ),
    ]
