# Generated by Django 3.0.3 on 2020-02-11 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspectv1', '0013_shyam'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shyam',
            options={},
        ),
        migrations.RemoveField(
            model_name='shyam',
            name='site_field',
        ),
        migrations.AddField(
            model_name='shyam',
            name='field_value',
            field=models.CharField(default=' ', max_length=100, verbose_name='value'),
        ),
        migrations.AddField(
            model_name='shyam',
            name='status',
            field=models.CharField(default=' ', max_length=100, verbose_name='checked'),
        ),
        migrations.AlterField(
            model_name='shyam',
            name='items',
            field=models.CharField(default=' ', max_length=100, verbose_name='items'),
        ),
    ]
