# Generated by Django 3.0.3 on 2020-02-11 13:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inspectv1', '0014_auto_20200211_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemincategory',
            name='category',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inspectv1.InspectionCategory', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='itemincategory',
            name='fieldtype',
            field=models.CharField(choices=[('checkbox', 'CheckBox'), ('text', 'Textfield'), ('number', 'NumberField'), ('date', 'DateField')], max_length=20),
        ),
        migrations.CreateModel(
            name='InspectionDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('com_lev', models.CharField(max_length=200, verbose_name='Competancy Level')),
                ('com_cert', models.CharField(max_length=200, verbose_name='Competancy Certificate')),
                ('signature', models.ImageField(upload_to=None)),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Inspectordetail',
                'verbose_name_plural': 'Inspectordetails',
            },
        ),
    ]
