# Generated by Django 3.0.3 on 2020-02-11 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspectv1', '0015_auto_20200211_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='sites',
            name='capacity',
            field=models.CharField(default=' ', max_length=300, verbose_name='Capacity'),
        ),
        migrations.AddField(
            model_name='sites',
            name='incomer',
            field=models.CharField(default=' ', max_length=300, verbose_name='Incomer'),
        ),
        migrations.AddField(
            model_name='sites',
            name='msbyear',
            field=models.CharField(default=' ', max_length=300, verbose_name='Msb Year'),
        ),
        migrations.AddField(
            model_name='sites',
            name='stoffice',
            field=models.CharField(default=' ', max_length=300, verbose_name='ST Office'),
        ),
        migrations.AddField(
            model_name='sites',
            name='subsdiary',
            field=models.CharField(default=' ', max_length=300, verbose_name='Subsdiary'),
        ),
    ]
