# Generated by Django 3.0.3 on 2020-02-11 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inspectv1', '0016_auto_20200211_1931'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shyam',
            name='sno',
        ),
    ]
