# Generated by Django 3.0.3 on 2020-02-15 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inspectv1', '0017_auto_20200215_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sites',
            name='stoffice',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='inspectv1.Stoffice'),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
