# Generated by Django 3.0.3 on 2020-02-12 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspectv1', '0017_remove_shyam_sno'),
    ]

    operations = [
        migrations.AddField(
            model_name='shyam',
            name='S_id',
            field=models.IntegerField(default='0', verbose_name='Site Id'),
        ),
    ]
