# Generated by Django 3.0.3 on 2020-02-12 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspectv1', '0018_shyam_s_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='shyam',
            name='Cat_id',
            field=models.IntegerField(default='0', verbose_name='Category Id'),
        ),
        migrations.AddField(
            model_name='shyam',
            name='Ins_id',
            field=models.IntegerField(default='0', verbose_name='Inspector Id'),
        ),
        migrations.AddField(
            model_name='shyam',
            name='item_id',
            field=models.IntegerField(default='0', verbose_name='Item Id'),
        ),
    ]
