# Generated by Django 3.0.3 on 2020-02-12 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspectv1', '0019_auto_20200212_1133'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Shyam',
            new_name='Inspected_Item',
        ),
        migrations.AlterModelOptions(
            name='inspected_item',
            options={'verbose_name': 'Inspeced_Item', 'verbose_name_plural': 'Inspected_Items'},
        ),
        migrations.AlterField(
            model_name='sites',
            name='subsdiary',
            field=models.CharField(choices=[('checkbox', 'CheckBox'), ('text', 'Textfield'), ('number', 'NumberField'), ('date', 'DateField')], max_length=300, verbose_name='Subsdiary'),
        ),
    ]
