# Generated by Django 3.0.3 on 2020-02-17 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inspectv1', '0020_auto_20200217_0729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sites',
            name='stoffice',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='inspectv1.Stoffice'),
        ),
    ]
