# Generated by Django 3.0.3 on 2020-02-12 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inspectv1', '0020_auto_20200212_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspected_item',
            name='cate',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='inspectv1.InspectionDetails'),
        ),
    ]
