# Generated by Django 3.0.3 on 2020-02-18 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inspectv1', '0021_auto_20200217_0822'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Inspect_Item',
            new_name='InspectItem',
        ),
        migrations.RemoveField(
            model_name='profileinterest',
            name='profile',
        ),
        migrations.AlterModelOptions(
            name='inspectitem',
            options={'verbose_name': 'InspectItem', 'verbose_name_plural': 'InspectItems'},
        ),
        migrations.AlterField(
            model_name='sites',
            name='stoffice',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='inspectv1.Stoffice'),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.DeleteModel(
            name='ProfileInterest',
        ),
    ]
