# Generated by Django 3.0.3 on 2020-02-12 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inspectv1', '0021_inspected_item_cate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inspected_item',
            name='Cat_id',
        ),
        migrations.RemoveField(
            model_name='inspected_item',
            name='cate',
        ),
        migrations.AddField(
            model_name='inspected_item',
            name='Cat',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='inspectv1.ItemInCategory'),
        ),
    ]
