# Generated by Django 3.0.3 on 2020-02-12 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inspectv1', '0022_auto_20200212_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspected_item',
            name='Cat',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='inspectv1.Inspected_Item'),
        ),
    ]
