# Generated by Django 3.0.3 on 2020-02-12 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspectv1', '0023_auto_20200212_1545'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inspected_item',
            name='Cat',
        ),
        migrations.AddField(
            model_name='inspected_item',
            name='Cat_id',
            field=models.IntegerField(default='0', verbose_name='Category Id'),
        ),
    ]
