# Generated by Django 3.0.3 on 2020-02-12 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inspectv1', '0024_auto_20200212_1547'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inspected_item',
            old_name='Cat_id',
            new_name='c_id',
        ),
        migrations.AddField(
            model_name='inspected_item',
            name='Cat',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='inspectv1.InspectionCategory'),
        ),
    ]
