# Generated by Django 3.0.3 on 2020-02-12 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inspectv1', '0025_auto_20200212_1609'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inspected_item',
            options={},
        ),
        migrations.RemoveField(
            model_name='inspected_item',
            name='Cat',
        ),
    ]
